# Setup
theme:        jekyll-theme-cayman
title:        MUG Roma Tre - Arduino Day 2017 Code Jam
tagline:        Arduino Day 2017 Code Jam
description:        Hackathon organizzato da MUG Roma Tre e Workco.

# Google Analytics
google_analytics: UA-49721875-1